### ISSUE TITLE
Hi ! some thing about rediarization module

### ISSUE THREAD

**Issue by YunJiao-Chen** [Rehan-Ahmad/SpeakerDiarization#1]
I  found in your code-- rediarization module
**line 44  from omp import omp** 
I search on google, can't found it.
I guess that module is not public python  module, is it?
and omp means Orthogonal Matching Pursuit?

hope U have a time to answer !

**Comment by Rehan-Ahmad** [comment]
Yes it was Orthogonal Matching Pursuit (OMP). Currently it is not used in the Diarization, so you can remove this line. I have also update the ReDiarization.py. Thanks.
